name: 'singapore_government_directory'
version: '1.0.0'
config-version: 2


profile: 'singapore_government_directory'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:       
  - "target"
  - "dbt_packages"

models:
  singapore_government_directory:
    staging:
      +materialized: view
      +schema: staging
    facts:
      +materialized: table
      +schema: facts
    dimensions:
      +materialized: table
      +schema: dimensions
    marts:
      +materialized: table
      +schema: marts
