ministries_url = {
    "Ministry of Culture, Community and Youth": "https://www.sgdi.gov.sg/ministries/mccy",
    "Ministry of Defence": "https://www.sgdi.gov.sg/ministries/mindef",
    "Ministry of Digital Development and Information": "https://www.sgdi.gov.sg/ministries/mddi",
    "Ministry of Education": "https://www.sgdi.gov.sg/ministries/moe",
    "Ministry of Finance": "https://www.sgdi.gov.sg/ministries/mof",
    "Ministry of Foreign Affairs": "https://www.sgdi.gov.sg/ministries/mfa",
    "Ministry of Health": "https://www.sgdi.gov.sg/ministries/moh",
    "Ministry of Home Affairs": "https://www.sgdi.gov.sg/ministries/mha",
    "Ministry of Law": "https://www.sgdi.gov.sg/ministries/minlaw",
    "Ministry of Manpower": "https://www.sgdi.gov.sg/ministries/mom",
    "Ministry of National Devleopment": "https://www.sgdi.gov.sg/ministries/mnd",
    "Ministry of Social and Family Development": "https://www.sgdi.gov.sg/ministries/msf",
    "Ministry of Sustainability and the Environment": "https://www.sgdi.gov.sg/ministries/mse",
    "Ministry of Trade and Industry": "https://www.sgdi.gov.sg/ministries/mti",
    "Ministry of Transport": "https://www.sgdi.gov.sg/ministries/mot",
    "Prime Minister's Office": "https://www.sgdi.gov.sg/ministries/pmo",
}

organs_of_state_url = {
    "ATTORNEY-GENERAL'S CHAMBERS": "https://www.sgdi.gov.sg/organs-of-state/agc",
    "AUDITOR-GENERAL'S OFFICE": "https://www.sgdi.gov.sg/organs-of-state/ago",
    "INDUSTRIAL ARBITRATION COURT": "https://www.sgdi.gov.sg/organs-of-state/iac",
    "ISTANA": "https://www.sgdi.gov.sg/organs-of-state/istana",
    "JUDICIARY, FAMILY JUSTICE COURTS": "https://www.sgdi.gov.sg/organs-of-state/fjcourts",
    "JUDICIARY, STATE COURTS": "https://www.sgdi.gov.sg/organs-of-state/state-courts",
    "JUDICIARY, SUPREME COURT": "https://www.sgdi.gov.sg/organs-of-state/supcourt",
    "PARLIAMENT OF SINGAPORE": "https://www.sgdi.gov.sg/organs-of-state/parl",
    "PUBLIC SERVICE COMMISSION": "https://www.sgdi.gov.sg/organs-of-state/psc",
    "THE CABINET": "https://www.sgdi.gov.sg/organs-of-state/cab",
}
